"""Domain models shared by pipeline modules."""

from ai_news_feed.domain.models import (
    Attachment,
    AttachmentKind,
    ClusterBatch,
    CollectionBatch,
    CollectionCursor,
    CollectionError,
    CollectorKind,
    DeliveryReceipt,
    Digest,
    DigestItem,
    DigestSendTime,
    DuplicateKind,
    DuplicateLink,
    ExactDeduplicationResult,
    InterestProfile,
    Material,
    NewsCluster,
    RawItem,
    ScreeningResult,
    SourceConfig,
    SourceKind,
)

__all__ = [
    "Attachment",
    "AttachmentKind",
    "ClusterBatch",
    "CollectionBatch",
    "CollectionCursor",
    "CollectionError",
    "CollectorKind",
    "DeliveryReceipt",
    "Digest",
    "DigestItem",
    "DigestSendTime",
    "DuplicateKind",
    "DuplicateLink",
    "ExactDeduplicationResult",
    "InterestProfile",
    "Material",
    "NewsCluster",
    "RawItem",
    "ScreeningResult",
    "SourceConfig",
    "SourceKind",
]
